version: '3.3'
services:
    db:
        image: mysql:5.7
        ports:
        - '1234:3306'

        
        environment:
            MYSQL_DATABASE: 'loanmanager'
            MYSQL_ROOT_PASSWORD: 'password'
        
    app:
        build: . 
        volumes:
            - .:/django
        ports:
            - 8000:8000
        image: app:django
        container_name: djapp
        command: sh -c "python manage.py makemigrations;python manage.py migrate; python manage.py loaddata whole.json;python manage.py runserver 0.0.0.0:8000"
        depends_on:
            - db